### ISSUE TITLE
Question: Will this get uploaded to Modrinth or Curseforge?

### ISSUE THREAD

**Issue by MageOfGaming** [immails/Geolosys-Next#2]
Title

**Comment by immails** [comment]
Guess i need to ask the mod author about this

**Comment by immails** [comment]
Now we wait

**Comment by immails** [comment]
The owner has answered my question and currently my fork is being under review on modrinth. then i'll publish it on curseforge a bit later

**Comment by immails** [comment]
@MageOfGaming anything else about your question? :)

**Comment by MageOfGaming** [comment]
> @MageOfGaming anything else about your question? :)

No, good to hear this being published on cf and modrinth! :D

**Comment by immails** [comment]
@MageOfGaming 
https://modrinth.com/mod/geolosys-next 
https://www.curseforge.com/minecraft/mc-mods/geolosys-next
