### ISSUE TITLE
Ore clusters not stacking, Other coals do not work as fuel. And ore generation seems wrong

### ISSUE THREAD

**Issue by Lordtrist76** [immails/Geolosys-Next#3]
## Versions: Minecraft 1.20.1

- Minecraft Forge: 1.20.1
- Geolosys:
- JourneyMap (optional):
- ImmersiveEngineering (optional):

**Comment by immails** [comment]
What about ore generations?

**Comment by immails** [comment]
@Lordtrist76 So what's about ore generation?

**Comment by Lordtrist76** [comment]
@immails Coal ore generation does not generate properly compared to the original mod, To name a few that has specific ore generations. Coal, Quarts, Iron. Etc. They have different ways they generate. The coal I have found in this mod doesn't generate properly as it should (It should generate in a big pancake almost formation, 1 block high but really spread out in a circle almost)
That's all I really noticed with the generation. Hope this helps, Thank you for responding!

**Comment by immails** [comment]
@Lordtrist76 I've released 8.0.3 with fuel and stack size fixes some hours ago. I'll check ore gen later.

**Comment by immails** [comment]
@Lordtrist76 After some research, using latest geolosys release and geolosys next, i've found out that everything seems to be the same? 
![изображение](https://github.com/user-attachments/assets/3bb7ebeb-966d-461b-a50b-86ac575e1b59)
![изображение](https://github.com/user-attachments/assets/4614a4f0-dd6e-4b10-abe7-06ebbeca225d)

**Comment by Lordtrist76** [comment]
@immails Hmm I must've just seen a weird vein then. Anyway I really appreciate you updating the mod and responding to bugs.
I'll let you know if I find any other bugs concerning the mod.

Cheers!
